apiVersion: branch.github.upbound.io/v1alpha1
kind: Branch
metadata:
  annotations:
    meta.upbound.io/example-id: branch/v1alpha1/branch
  labels:
    testing.upbound.io/example-name: development
  name: development
spec:
  forProvider:
    repositorySelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

